version: "3"

services:
  streamlit:
    image: matcom/streamlit:latest
    container_name: covidsim
    build: .
    ports:
      - 8501:8501
    volumes:
      - ./:/src
    command: ["streamlit", "run", "dashboard.py"]
